import type { Atendimento } from "../../Atendimentos/types/types";

export const SOLICITACOES_MOCK: Atendimento[] = [
  {
    id: 1,
    numero: "67894",
    nome: "Gustavo",
    titulo: "Outro problema",
    local: "Desenvolvimento front-end",
    mensagem: "Meu PC está desligando toda hora",
    status: "Resolvido",
    horario: "10/09/2025 - 10:09",
  },
  {
    id: 2,
    numero: "67895",
    nome: "Gustavo",
    titulo: "Requisição de Papel",
    mensagem: "Impressora do setor está sem papel",
    status: "Em atendimento",
    horario: "13/10/2025 - 15:09",
  },
  {
    id: 3,
    numero: "67896",
    nome: "Gustavo",
    local: "Desenvolvimento front-end",
    titulo: "Problema com o Mecauto",
    mensagem: "Erro ao acessar o sistema Mecauto",
    status: "Pendente",
    horario: "10/09/2025 - 10:09",
  },
  {
    id: 4,
    numero: "67897",
    nome: "Gustavo",
    local: "Desenvolvimento front-end",
    titulo: "Problema com equipamento",
    mensagem: "Computador travando constantemente",
    status: "Resolvido",
    horario: "10/09/2025 - 10:09",
  },
  {
    id: 5,
    numero: "67898",
    nome: "Gustavo",
    local: "Desenvolvimento front-end",
    titulo: "Problema com equipamento",
    mensagem: "Internet muito lenta no setor",
    status: "Pendente",
    horario: "10/09/2025 - 10:09",
  },
  {
    id: 6,
    numero: "67899",
    nome: "Gustavo",
    local: "Desenvolvimento front-end",
    titulo: "Problema com o meu ramal",
    mensagem: "Telefone sem sinal para chamadas",
    status: "Resolvido",
    horario: "10/09/2025 - 10:09",
  },
  {
    id: 7,
    numero: "67900",
    nome: "Gustavo",
    local: "Desenvolvimento front-end",
    titulo: "Troca de Toner",
    mensagem: "Impressora solicitando troca de toner",
    status: "Em atendimento",
    horario: "10/09/2025 - 10:09",
  },
];
