import type { Atendimento } from "../types/types";

export const ATENDIMENTOS_MOCK: Atendimento[] = [
  {
    id: 1,
    numero: "67894",
    titulo: "Outro problema",
    nome: "Gustavo",
    local: "Financeiro",
    mensagem: "Meu PC está desligando toda hora",
    status: "pendente",
    horario: "10/02/2024 - 09:00",
  },
  {
    id: 2,
    numero: "67895",
    titulo: "Problema com impressora",
    nome: "Erika",
    local: "Caixa",
    mensagem: "Impressora não imprime",
    status: "aberto",
    horario: "10/02/2024 - 10:30",
  },
  {
    id: 3,
    numero: "67896",
    titulo: "Internet lenta",
    nome: "Carlos",
    local: "Marketing",
    mensagem: "A internet está muito lenta",
    status: "pendente",
    horario: "10/02/2024 - 11:15",
  },
  {
    id: 4,
    numero: "67897",
    titulo: "Erro no sistema",
    nome: "Juliana",
    local: "RH",
    mensagem: "Sistema não abre na inicialização",
    status: "aberto",
    horario: "10/02/2024 - 13:40",
  },
  {
    id: 5,
    numero: "67898",
    titulo: "Solicitação de acesso",
    nome: "Marcos",
    local: "Compras",
    mensagem: "Preciso de acesso ao sistema interno",
    status: "resolvido",
    horario: "10/02/2024 - 14:20",
  },
  {
    id: 6,
    numero: "67899",
    titulo: "Computador travando",
    nome: "Fernanda",
    local: "Contabilidade",
    mensagem: "O computador trava ao abrir planilhas",
    status: "pendente",
    horario: "10/02/2024 - 15:05",
  },
  {
    id: 7,
    numero: "67900",
    titulo: "Teclado não funciona",
    nome: "Rafael",
    local: "Logística",
    mensagem: "Algumas teclas não respondem",
    status: "aberto",
    horario: "10/02/2024 - 16:10",
  },
  {
    id: 8,
    numero: "67901",
    titulo: "Monitor sem imagem",
    nome: "Patricia",
    local: "Recepção",
    mensagem: "Monitor liga mas não mostra imagem",
    status: "pendente",
    horario: "10/02/2024 - 17:45",
  },
];
